### ISSUE TITLE
CSS Customizations?

### ISSUE THREAD

**Issue by bronestly** [stuebersystems/gitbook-plugin-bootstrap-callout#1]
Hey there

First of all: love your plugin, since the other one does not work and is not maintained anymore. :)

Question: How can I add some of my own CSS customizations?
For example I would like to add a colored background to all boxes (green bg for success box, etc...)

**Comment by fstueber** [comment]
Hi, to do your own CSS customization:
- Create a website.css file in your GitBook. See https://gitbookio.gitbooks.io/documentation/content/styling/book.html for more.
- Add the following css style to this file to make the background of a success callout green.
  `.callout-success { background-color: green; }` 
- Save and check

Please keep in mind that the user can switch between different themes. To support all 3 main themes you can do the following:

```
.callout-success { background-color: green; }
.book.color-theme-1 .callout-success { background-color: yellow; }
.book.color-theme-2 .callout-success { background-color: red; }
```

You can inspect the generated Gitbook HTML in your browser to get an overview on other CSS classes like `.callout-primary`, `.callout-warning` etc.
